name: Deploy CDK

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
  pull_request_target:
    types: [closed]

env:
  AWS_REGION: us-east-1
  CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}

permissions:
  id-token: write
  contents: read

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.set.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed services
        id: set
        run: |
          git fetch origin main
          changed=$(git diff --name-only origin/main...HEAD | grep -Eo '^services/[^/]+' | cut -d '/' -f2 | sort -u | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "Changed services: $changed"
          echo "changed=$changed" >> $GITHUB_OUTPUT

  deploy-pr:
    if: github.event_name == 'pull_request'
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.changed) }}
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python and CDK
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: npm install -g aws-cdk

      - name: Install requirements
        run: |
          pip install -r services/${{ matrix.service }}/infra/requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Preview Stack
        run: |
          SERVICE_NAME=${{ matrix.service }}
          PASCAL_CASE_NAME=$(echo "$SERVICE_NAME" | awk -F'_' 'BEGIN{OFS=""} { for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2); print }')
          STACK_NAME="${PASCAL_CASE_NAME}Stack-pr-${PR_NUMBER}"

          echo "Deploying stack: $STACK_NAME"
          cdk deploy "$STACK_NAME" \
            --app "python3 services/${SERVICE_NAME}/infra/app.py" \
            --context env=pr \
            --context pr_number=${PR_NUMBER} \
            --require-approval never

  deploy-int:
      if: github.ref == 'refs/heads/main'
      needs: detect-changes
      runs-on: ubuntu-latest
      strategy:
        matrix:
          service: ${{ fromJson(needs.detect-changes.outputs.changed) }}

      steps:
        - uses: actions/checkout@v4

        - name: Setup Python and CDK
          uses: actions/setup-python@v5
          with:
            python-version: "3.11"

        - run: npm install -g aws-cdk

        - name: Install requirements
          run: |
            pip install -r services/${{ matrix.service }}/infra/requirements.txt

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole
            aws-region: ${{ env.AWS_REGION }}

        - name: Deploy Int Stack
          run: |
            SERVICE_NAME=${{ matrix.service }}
            PASCAL_CASE_NAME=$(echo "$SERVICE_NAME" | awk -F'_' 'BEGIN{OFS=""} { for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2); print }')
            STACK_NAME="${PASCAL_CASE_NAME}Stack-int"

            echo "Deploying stack: $STACK_NAME"
            cdk deploy "$STACK_NAME" \
              --app "python3 services/${SERVICE_NAME}/infra/app.py" \
              --context env=int \
              --require-approval never

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.changed) }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python and CDK
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: npm install -g aws-cdk

      - name: Install requirements
        run: |
          pip install -r services/${{ matrix.service }}/infra/requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Production Stack
        run: |
          SERVICE_NAME=${{ matrix.service }}
          PASCAL_CASE_NAME=$(echo "$SERVICE_NAME" | awk -F'_' 'BEGIN{OFS=""} { for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2); print }')
          STACK_NAME="${PASCAL_CASE_NAME}Stack-prod"

          echo "Deploying stack: $STACK_NAME"
          cdk deploy "$STACK_NAME" \
            --app "python3 services/${SERVICE_NAME}/infra/app.py" \
            --context env=prod \
            --require-approval never

  destroy-pr:
    if: github.event.pull_request.merged == false && github.event.action == 'closed'
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.changed) }}
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}

    steps:
      - uses: actions/checkout@v4

      - run: npm install -g aws-cdk

      - name: Install requirements
        run: |
          pip install -r services/${{ matrix.service }}/infra/requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Destroy PR Preview Stack
        run: |
          SERVICE_NAME=${{ matrix.service }}
          PASCAL_CASE_NAME=$(echo "$SERVICE_NAME" | awk -F'_' 'BEGIN{OFS=""} { for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2); print }')
          STACK_NAME="${PASCAL_CASE_NAME}Stack-pr-${PR_NUMBER}"

          echo "Destroying stack: $STACK_NAME"
          cdk destroy "$STACK_NAME" --force
