name: Deploy Host UI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize]

env:
  AWS_REGION: us-east-1
  CDK_DEFAULT_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps and generate static site
        working-directory: microfrontends/host_ui
        env:
          # Set API base for generated SPA; adjust to your int/prod URLs as needed
          HOST_API_BASE: ${{ github.event_name == 'pull_request' && 'https://example-pr-host-bff' || 'https://example-int-host-bff' }}
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install --no-fund --no-audit; fi
          npm run generate

      - name: Setup Python and CDK
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: npm install -g aws-cdk

      - name: Install infra requirements
        working-directory: microfrontends/host_ui/infra
        run: |
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Host UI
        working-directory: microfrontends/host_ui/infra
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            cdk deploy "HostUiStack-pr-${{ github.event.pull_request.number }}" \
              --app "python3 app.py" \
              --context env=pr \
              --context pr_number=${{ github.event.pull_request.number }} \
              --require-approval never
          else
            cdk deploy "HostUiStack-int" \
              --app "python3 app.py" \
              --context env=int \
              --require-approval never
          fi

